### ISSUE TITLE
Moderators need to be able to disable plugins

### ISSUE THREAD

**Issue by WiggleWizard** [Zinglish/alice#9]
Perhaps in the plugin config, under the section if the moderator puts `disabled = 1/true` it won't load the plugin?

**Comment by dschoerk** [comment]
a plugin is only added to the plugin list if it has a priority
otherwise a warning is printed when Alice attempts to load the plugin
to disable a plugin in the cfg file either delete the priority Setting or comment it out with a hash (altering the Name such it doesnt match the plugins Name)
init   is called while loading the module, but since we use on_plugin_init for initialization this shouldnt be a problem
https://github.com/Zinglish/alice/commit/72ffe77004c833cccd5095c268f3ac46aa9e0b45
